"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import {
  Plus, X, ChevronDown, ArrowLeft, Save, Loader2,
  Briefcase, Lightbulb, History, Sparkles, PenLine,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { scoreSpecialistProfile, type ScoreResult } from "@/lib/expert/quality-score";
import { PdlExperiencePicker } from "./pdl-experience-picker";
import { AutocompleteInput } from "@/components/ui/autocomplete-input";
import { MonthYearPicker } from "@/components/ui/month-year-picker";
import { CompanySearch } from "@/components/ui/company-search";

interface PdlExperience {
  company: { name: string; website?: string | null; industry?: string | null };
  title: string;
  startDate?: string | null;
  endDate?: string | null;
  isCurrent?: boolean;
  summary?: string;
}

interface WorkExample {
  title: string;
  subject: string;
  companyName: string;
  companyIndustry: string;
  startDate: string;
  endDate: string;
  isCurrent: boolean;
  isPdlSource: boolean;
  pdlExperienceIndex?: number;
  exampleType: "project" | "role";
  saveToHistory?: boolean;
}

const EMPTY_EXAMPLE: WorkExample = {
  title: "",
  subject: "",
  companyName: "",
  companyIndustry: "",
  startDate: "",
  endDate: "",
  isCurrent: false,
  isPdlSource: false,
  exampleType: "project",
  saveToHistory: false,
};

const SUBJECT_MAX_CHARS = 500;

interface EditorProps {
  expertId: string;
  initialProfile?: {
    id?: string;
    title?: string | null;
    bodyDescription?: string | null;
    skills?: string[] | null;
    industries?: string[] | null;
    services?: string[] | null;
    examples?: WorkExample[];
  } | null;
  pdlExperiences?: PdlExperience[];
  expertBio?: string;
  onSave?: (spId: string) => void;
  onCancel?: () => void;
}

// ─── Smart search helpers ────────────────────────────────

async function searchSkills(query: string): Promise<string[]> {
  try {
    const res = await fetch(`/api/taxonomy/skills/search?q=${encodeURIComponent(query)}`);
    const data = await res.json();
    return (data.results ?? []).map((r: { name: string }) => r.name);
  } catch {
    return [];
  }
}

async function searchIndustries(query: string): Promise<string[]> {
  try {
    const res = await fetch(`/api/taxonomy/industries/search?q=${encodeURIComponent(query)}`);
    const data = await res.json();
    return data.results ?? [];
  } catch {
    return [];
  }
}

// ─── AI condense helper ──────────────────────────────────

async function condenseSummary(summary: string, roleTitle: string, companyName: string): Promise<string> {
  if (!summary || summary.length <= 500) return summary;
  try {
    const res = await fetch("/api/ai/condense-summary", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ summary, roleTitle, companyName }),
    });
    const data = await res.json();
    return data.condensed ?? summary.slice(0, 500);
  } catch {
    return summary.slice(0, 500);
  }
}

// ─── Main Editor ─────────────────────────────────────────

export function SpecialistProfileEditor({
  expertId,
  initialProfile,
  pdlExperiences = [],
  expertBio,
  onSave,
  onCancel,
}: EditorProps) {
  const isEditing = !!initialProfile?.id;
  const [title, setTitle] = useState(initialProfile?.title ?? "");
  const [bodyDescription, setBodyDescription] = useState(
    initialProfile?.bodyDescription ?? ""
  );
  const [skills, setSkills] = useState<string[]>(initialProfile?.skills ?? []);
  const [industries, setIndustries] = useState<string[]>(
    initialProfile?.industries ?? []
  );
  const [examples, setExamples] = useState<WorkExample[]>(
    initialProfile?.examples?.length ? initialProfile.examples : []
  );

  const [score, setScore] = useState<ScoreResult | null>(null);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showPdlPicker, setShowPdlPicker] = useState(false);
  const [pickerTargetIdx, setPickerTargetIdx] = useState<number>(0);
  const [generating, setGenerating] = useState(false);
  const hasAutoGenerated = useRef(false);

  // Check if all 3 examples have subjects filled
  const allExamplesComplete = examples.length >= 3 &&
    examples.every((ex) => ex.title.trim() && ex.subject.trim());

  // Show description section if: editing with existing description, OR all 3 examples complete
  const showDescription = (isEditing && bodyDescription.length > 0) || allExamplesComplete;

  // Auto-generate description when it first becomes visible
  useEffect(() => {
    if (showDescription && !bodyDescription && !hasAutoGenerated.current && title.trim() && examples.length >= 3) {
      hasAutoGenerated.current = true;
      handleGenerateDescription();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [showDescription]);

  // Recompute score whenever inputs change
  useEffect(() => {
    const result = scoreSpecialistProfile({
      title,
      bodyDescription,
      industries,
      examples,
    });
    setScore(result);
  }, [title, bodyDescription, industries, examples]);

  const updateExample = useCallback(
    (idx: number, patch: Partial<WorkExample>) => {
      setExamples((prev) =>
        prev.map((ex, i) => (i === idx ? { ...ex, ...patch } : ex))
      );
    },
    []
  );

  const addExample = useCallback(() => {
    if (examples.length >= 3) return;
    setExamples((prev) => [...prev, { ...EMPTY_EXAMPLE }]);
  }, [examples.length]);

  const removeExample = useCallback((idx: number) => {
    setExamples((prev) => prev.filter((_, i) => i !== idx));
  }, []);

  const handlePdlSelect = useCallback(
    async (ex: PdlExperience, pdlIdx: number) => {
      // Condense PDL summary via AI if it's long or has bullets
      let subject = ex.summary ?? "";
      if (subject && (subject.length > 500 || subject.includes("\n") || subject.includes("•"))) {
        subject = await condenseSummary(subject, ex.title, ex.company.name);
      }

      const newEx: WorkExample = {
        title: ex.title,
        subject,
        companyName: ex.company.name,
        companyIndustry: ex.company.industry ?? "",
        startDate: ex.startDate ?? "",
        endDate: ex.endDate ?? "",
        isCurrent: ex.isCurrent ?? false,
        isPdlSource: true,
        pdlExperienceIndex: pdlIdx,
        exampleType: "role",
      };

      if (pickerTargetIdx < examples.length) {
        updateExample(pickerTargetIdx, newEx);
      } else if (examples.length < 3) {
        setExamples((prev) => [...prev, newEx]);
      }
    },
    [pickerTargetIdx, examples.length, updateExample]
  );

  const handleGenerateDescription = async () => {
    if (!title.trim() || examples.length < 3) return;
    setGenerating(true);
    try {
      const res = await fetch(`/api/experts/${expertId}/specialist-profiles/generate-description`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title,
          examples: examples.map((ex) => ({
            title: ex.title,
            subject: ex.subject,
            companyName: ex.companyName,
            companyIndustry: ex.companyIndustry,
          })),
          bio: expertBio,
        }),
      });
      if (res.ok) {
        const data = await res.json();
        if (data.description) setBodyDescription(data.description);
      }
    } catch {
      // silently fail
    } finally {
      setGenerating(false);
    }
  };

  const handleSave = async () => {
    setSaving(true);
    setError(null);
    try {
      const url = isEditing
        ? `/api/experts/${expertId}/specialist-profiles/${initialProfile!.id}`
        : `/api/experts/${expertId}/specialist-profiles`;
      const method = isEditing ? "PUT" : "POST";

      const res = await fetch(url, {
        method,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title,
          bodyDescription,
          skills,
          industries,
          services: [],
          examples,
        }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error ?? "Save failed");
      }

      for (const ex of examples) {
        if (ex.saveToHistory && !ex.isPdlSource && ex.title && ex.companyName) {
          fetch(`/api/experts/${expertId}/work-history`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              title: ex.title,
              companyName: ex.companyName,
              companyIndustry: ex.companyIndustry,
              startDate: ex.startDate,
              endDate: ex.endDate,
              isCurrent: ex.isCurrent,
              subject: ex.subject,
            }),
          }).catch(() => {});
        }
      }

      const data = await res.json();
      const spId = isEditing ? initialProfile!.id! : data.specialistProfile?.id;
      onSave?.(spId);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Save failed");
    } finally {
      setSaving(false);
    }
  };

  const statusColor =
    score?.status === "strong"
      ? "text-cos-signal"
      : score?.status === "partial"
        ? "text-cos-electric"
        : score?.status === "weak"
          ? "text-cos-warm"
          : "text-cos-slate-dim";

  const barWidth = score ? `${score.score}%` : "0%";
  const barColor =
    score?.status === "strong"
      ? "bg-cos-signal"
      : score?.status === "partial"
        ? "bg-cos-electric"
        : "bg-cos-warm";

  return (
    <div className="cos-scrollbar mx-auto max-w-2xl space-y-4 overflow-y-auto p-6">
      {/* Back / cancel */}
      {onCancel && (
        <button
          onClick={onCancel}
          className="flex items-center gap-1.5 text-xs text-cos-slate-dim hover:text-cos-midnight transition-colors"
        >
          <ArrowLeft className="h-3.5 w-3.5" />
          Back to profile
        </button>
      )}

      <h2 className="font-heading text-lg font-semibold text-cos-midnight">
        {isEditing ? "Edit Specialist Profile" : "New Specialist Profile"}
      </h2>

      {/* ─── Guidance text ─────────────────────────────── */}
      <div className="rounded-cos-xl border border-cos-electric/20 bg-cos-electric/5 p-4">
        <div className="flex items-start gap-3">
          <Lightbulb className="h-4 w-4 shrink-0 text-cos-electric mt-0.5" />
          <p className="text-xs leading-relaxed text-cos-slate">
            Specialist profiles show your true expertise. Your work history doesn&apos;t always
            highlight where you excel &mdash; with enough experience, many experts tell their
            story through multiple unique specialist profiles. Avoid generic stories. Focus on
            one thing you want to be known for: a certain type of role, a special skill, or an
            industry expertise.
          </p>
        </div>
      </div>

      {/* ─── Title + Taxonomy ────────────────────────── */}
      <div className="rounded-cos-xl border border-cos-border bg-cos-surface p-4 space-y-3">
        <label className="block">
          <span className="text-xs font-semibold text-cos-midnight">
            Specialist Title
          </span>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder='e.g. "Fractional CMO for B2B SaaS"'
            className="mt-1.5 w-full rounded-cos-md border border-cos-border bg-white px-3 py-2 text-sm text-cos-midnight placeholder:text-cos-slate-light focus:border-cos-electric focus:outline-none"
          />
        </label>

        <AutocompleteInput
          label="Skills"
          placeholder="Type to search skills (e.g. Tableau, SEO, Python)..."
          values={skills}
          onChange={setSkills}
          fetchSuggestions={searchSkills}
          color="midnight"
        />

        <AutocompleteInput
          label="Industries"
          placeholder="Type to search industries (e.g. SaaS, FinTech, Healthcare)..."
          values={industries}
          onChange={setIndustries}
          fetchSuggestions={searchIndustries}
          color="signal"
        />
      </div>

      {/* ─── Work Examples ─────────────────────────────── */}
      <div className="rounded-cos-xl border border-cos-electric/20 bg-cos-electric/5 p-4 space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Briefcase className="h-4 w-4 text-cos-electric" />
            <p className="text-xs font-semibold text-cos-midnight">Work Examples</p>
          </div>
          <div className="flex items-center gap-2">
            {[1, 2, 3].map((n) => (
              <span
                key={n}
                className={cn(
                  "flex h-5 w-5 items-center justify-center rounded-full text-[10px] font-bold",
                  n <= examples.length
                    ? "bg-cos-signal text-white"
                    : "bg-cos-border text-cos-slate-light"
                )}
              >
                {n}
              </span>
            ))}
          </div>
        </div>

        {/* Guidance text */}
        {title.trim() ? (
          <p className="text-xs leading-relaxed text-cos-slate">
            Your three work examples are proof points for your expertise:{" "}
            <strong className="text-cos-midnight">&ldquo;{title}&rdquo;</strong>.
            Pick three examples &mdash; they could be roles from your work history, but they
            could also be projects you&apos;ve taken on at any point in your career or even
            something you did while working for another firm. This is your personal experience.
          </p>
        ) : (
          <p className="text-xs text-cos-slate-dim italic">
            Enter a specialist title above to see guidance for your work examples.
          </p>
        )}

        {/* Progress requirement banner */}
        {examples.length < 3 && (
          <div className="rounded-cos-lg border border-cos-warm/30 bg-cos-warm/8 px-3 py-2">
            <p className="text-[11px] font-medium text-cos-warm">
              {examples.length === 0
                ? "Add 3 work examples to continue. Choose from your work history or create new ones."
                : `${3 - examples.length} more example${3 - examples.length > 1 ? "s" : ""} required to generate your profile description.`}
            </p>
          </div>
        )}

        {/* Example cards */}
        {examples.map((ex, idx) => (
          <ExampleForm
            key={idx}
            index={idx}
            total={3}
            example={ex}
            onChange={(patch) => updateExample(idx, patch)}
            onRemove={() => removeExample(idx)}
          />
        ))}

        {/* Add example buttons — side by side, colorful */}
        {examples.length < 3 && (
          <div className="grid grid-cols-2 gap-2">
            {pdlExperiences.length > 0 && (
              <button
                onClick={() => {
                  setPickerTargetIdx(examples.length);
                  setShowPdlPicker(true);
                }}
                className="flex items-center justify-center gap-2 rounded-cos-lg bg-cos-signal/10 border border-cos-signal/30 py-3 text-xs font-medium text-cos-signal transition-colors hover:bg-cos-signal/20"
              >
                <History className="h-4 w-4" />
                <span>
                  From Work History
                  <span className="ml-1 rounded-cos-pill bg-cos-signal/20 px-1.5 py-0.5 text-[9px] font-bold">
                    {pdlExperiences.length}
                  </span>
                </span>
              </button>
            )}
            <button
              onClick={addExample}
              className={cn(
                "flex items-center justify-center gap-2 rounded-cos-lg border py-3 text-xs font-medium transition-colors",
                "bg-cos-electric/10 border-cos-electric/30 text-cos-electric hover:bg-cos-electric/20",
                pdlExperiences.length === 0 && "col-span-2"
              )}
            >
              <PenLine className="h-4 w-4" />
              New Work Example
            </button>
          </div>
        )}
      </div>

      {/* ─── Description (appears after 3 complete examples) ── */}
      {showDescription && (
        <div className="rounded-cos-xl border border-cos-border bg-cos-surface p-4 space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-cos-midnight">
              Profile Description
            </span>
            <div className="flex items-center gap-2">
              <span className="text-[10px] text-cos-slate-dim">
                {bodyDescription.length} chars
                {bodyDescription.length < 100 ? ` (need ${100 - bodyDescription.length} more)` : ""}
              </span>
              {title.trim() && examples.length >= 3 && (
                <button
                  onClick={handleGenerateDescription}
                  disabled={generating}
                  className="flex items-center gap-1 rounded-cos-md bg-cos-electric/10 px-2 py-1 text-[10px] font-medium text-cos-electric hover:bg-cos-electric/20 disabled:opacity-50 transition-colors"
                >
                  {generating ? (
                    <Loader2 className="h-3 w-3 animate-spin" />
                  ) : (
                    <Sparkles className="h-3 w-3" />
                  )}
                  {generating ? "Generating..." : bodyDescription ? "Regenerate" : "Generate with AI"}
                </button>
              )}
            </div>
          </div>
          {generating && !bodyDescription ? (
            <div className="flex items-center justify-center py-8 gap-2 text-cos-electric">
              <Loader2 className="h-5 w-5 animate-spin" />
              <span className="text-xs">Generating your specialist description...</span>
            </div>
          ) : (
            <textarea
              value={bodyDescription}
              onChange={(e) => setBodyDescription(e.target.value)}
              rows={6}
              placeholder="A compelling description of this expertise niche will be generated based on your title and work examples. You can also write your own."
              className="w-full resize-none rounded-cos-md border border-cos-border bg-white px-3 py-2 text-sm leading-relaxed text-cos-midnight placeholder:text-cos-slate-light focus:border-cos-electric focus:outline-none"
            />
          )}
        </div>
      )}

      {/* ─── Quality Score ─────────────────────────────── */}
      {score && (
        <div className="rounded-cos-xl border border-cos-border bg-cos-surface p-4 space-y-2">
          <div className="flex items-center justify-between">
            <p className="text-xs font-semibold text-cos-midnight">Quality Score</p>
            <span className={cn("text-sm font-bold", statusColor)}>
              {score.score}/100 &middot; {score.status.toUpperCase()}
            </span>
          </div>

          <div className="h-2 rounded-cos-full bg-cos-cloud-dim overflow-hidden">
            <div
              className={cn("h-full rounded-cos-full transition-all duration-500", barColor)}
              style={{ width: barWidth }}
            />
          </div>

          <div className="flex flex-wrap gap-1 pt-1">
            <ScoreChip label="Title" pts={score.breakdown.title} max={15} />
            <ScoreChip label="Description" pts={score.breakdown.bodyLength + score.breakdown.bodyDepth} max={25} />
            <ScoreChip label="Examples" pts={score.breakdown.example1 + score.breakdown.example2 + score.breakdown.example3} max={30} />
            <ScoreChip label="Completeness" pts={score.breakdown.exampleCompleteness} max={15} />
            <ScoreChip label="Coherence" pts={score.breakdown.coherence} max={15} />
          </div>

          {score.hints.length > 0 && (
            <div className="space-y-1 pt-1">
              {score.hints.map((hint, i) => (
                <p key={i} className="flex items-start gap-1.5 text-[11px] text-cos-slate-dim">
                  <span className="mt-0.5 shrink-0 text-cos-warm">&rarr;</span>
                  {hint}
                </p>
              ))}
            </div>
          )}

          {score.status === "strong" && (
            <p className="text-[11px] text-cos-signal font-medium">
              This profile will auto-publish and appear in search results.
            </p>
          )}
        </div>
      )}

      {/* ─── Error / Save ──────────────────────────────── */}
      {error && (
        <p className="rounded-cos-md bg-cos-ember/8 border border-cos-ember/20 px-3 py-2 text-xs text-cos-ember">
          {error}
        </p>
      )}

      <div className="flex items-center gap-3">
        <button
          onClick={handleSave}
          disabled={saving}
          className="flex items-center gap-2 rounded-cos-lg bg-cos-electric px-5 py-2.5 text-sm font-medium text-white transition-colors hover:bg-cos-electric/90 disabled:opacity-50"
        >
          {saving ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : (
            <Save className="h-4 w-4" />
          )}
          {saving ? "Saving..." : "Save profile"}
        </button>
        {onCancel && (
          <button
            onClick={onCancel}
            className="text-sm text-cos-slate-dim hover:text-cos-midnight transition-colors"
          >
            Cancel
          </button>
        )}
      </div>

      {/* Work History picker slide-over */}
      {showPdlPicker && (
        <PdlExperiencePicker
          experiences={pdlExperiences}
          onSelect={handlePdlSelect}
          onClose={() => setShowPdlPicker(false)}
        />
      )}
    </div>
  );
}

// ─── Sub-components ──────────────────────────────────────

function ExampleForm({
  index,
  total,
  example,
  onChange,
  onRemove,
}: {
  index: number;
  total: number;
  example: WorkExample;
  onChange: (patch: Partial<WorkExample>) => void;
  onRemove: () => void;
}) {
  const [expanded, setExpanded] = useState(true);
  const subjectLen = example.subject.length;

  return (
    <div className="rounded-cos-lg border border-cos-border/60 bg-white">
      <button
        onClick={() => setExpanded(!expanded)}
        className="flex w-full items-center gap-2 px-3 py-2.5 text-left"
      >
        <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-cos-electric/10 text-[10px] font-semibold text-cos-electric">
          {index + 1}
        </span>
        <p className="flex-1 truncate text-xs font-medium text-cos-midnight">
          {example.title || `Example ${index + 1} of ${total}`}
        </p>
        <div className="flex items-center gap-1.5">
          {example.isPdlSource && (
            <span className="rounded-cos-pill bg-cos-signal/10 px-1.5 py-0.5 text-[8px] font-medium text-cos-signal">
              From History
            </span>
          )}
          <button
            onClick={(e) => { e.stopPropagation(); onRemove(); }}
            className="rounded-cos-md p-0.5 text-cos-slate-light hover:text-cos-ember transition-colors"
          >
            <X className="h-3.5 w-3.5" />
          </button>
          <ChevronDown
            className={cn(
              "h-3.5 w-3.5 text-cos-slate-light transition-transform",
              expanded && "rotate-180"
            )}
          />
        </div>
      </button>

      {expanded && (
        <div className="border-t border-cos-border/30 px-3 pb-3 pt-2.5 space-y-2">
          <input
            type="text"
            value={example.title}
            onChange={(e) => onChange({ title: e.target.value })}
            placeholder='Title - e.g. "Rebuilt GTM for Series B Fintech" or "VP Marketing"'
            className="w-full rounded-cos-md border border-cos-border bg-cos-cloud/30 px-2.5 py-1.5 text-xs text-cos-midnight placeholder:text-cos-slate-light focus:border-cos-electric focus:outline-none"
          />

          <div>
            <textarea
              value={example.subject}
              onChange={(e) => {
                if (e.target.value.length <= SUBJECT_MAX_CHARS) {
                  onChange({ subject: e.target.value });
                }
              }}
              rows={3}
              placeholder="What did you do and what was the outcome? (2-3 sentences)"
              className="w-full resize-none rounded-cos-md border border-cos-border bg-cos-cloud/30 px-2.5 py-1.5 text-xs leading-relaxed text-cos-midnight placeholder:text-cos-slate-light focus:border-cos-electric focus:outline-none"
            />
            <div className="flex justify-end mt-0.5">
              <span className={cn(
                "text-[9px]",
                subjectLen > SUBJECT_MAX_CHARS * 0.9 ? "text-cos-ember" : "text-cos-slate-light"
              )}>
                {subjectLen}/{SUBJECT_MAX_CHARS}
              </span>
            </div>
          </div>

          <div className="flex gap-2">
            <CompanySearch
              value={example.companyName}
              industry={example.companyIndustry}
              onSelect={({ name, industry }) =>
                onChange({ companyName: name, companyIndustry: industry })
              }
              placeholder="Search companies..."
            />
            <input
              type="text"
              value={example.companyIndustry}
              onChange={(e) => onChange({ companyIndustry: e.target.value })}
              placeholder="Industry (auto-filled)"
              className="w-32 shrink-0 rounded-cos-md border border-cos-border bg-cos-cloud/30 px-2.5 py-1.5 text-xs text-cos-midnight placeholder:text-cos-slate-light focus:border-cos-electric focus:outline-none"
            />
          </div>

          <div className="flex items-center gap-2">
            <div className="flex-1">
              <MonthYearPicker
                value={example.startDate}
                onChange={(val) => onChange({ startDate: val })}
                placeholder="Start date"
              />
            </div>
            <div className="flex-1">
              <MonthYearPicker
                value={example.endDate}
                onChange={(val) => onChange({ endDate: val })}
                placeholder="End date"
                disabled={example.isCurrent}
              />
            </div>
            <label className="flex items-center gap-1 text-[10px] text-cos-slate-dim cursor-pointer shrink-0">
              <input
                type="checkbox"
                checked={example.isCurrent}
                onChange={(e) =>
                  onChange({ isCurrent: e.target.checked, endDate: "" })
                }
                className="rounded"
              />
              Current
            </label>
          </div>

          {!example.isPdlSource && (
            <label className="flex items-center gap-2 pt-1 text-[10px] text-cos-slate cursor-pointer">
              <input
                type="checkbox"
                checked={example.saveToHistory ?? false}
                onChange={(e) => onChange({ saveToHistory: e.target.checked })}
                className="rounded"
              />
              Save to my Work History for future use
            </label>
          )}
        </div>
      )}
    </div>
  );
}

function ScoreChip({ label, pts, max }: { label: string; pts: number; max: number }) {
  const full = pts >= max;
  return (
    <span
      className={cn(
        "rounded-cos-pill px-2 py-0.5 text-[10px] font-medium",
        full
          ? "bg-cos-signal/10 text-cos-signal"
          : pts > 0
            ? "bg-cos-electric/10 text-cos-electric"
            : "bg-cos-cloud-dim text-cos-slate-dim"
      )}
    >
      {full ? "\u2713 " : pts > 0 ? "\u25D1 " : "\u25CB "}
      {label} ({pts}/{max})
    </span>
  );
}
